= Triggers
:Author:    Wilhelmus G.J. Velzeboer
:Email:     wim@velzeboer.nl
:Date:      March 2021
:Revision:  version 1

== Trigger class

=== Naming conventions
Use the plural name of your Custom Object for the name of your trigger.

 Some bad examples are
 TriggerRace.cls and RaceTrigger

 Some good examples are
 Races.Trigger and Teams.Trigger

=== Example

*Application*
[source, java]
----
public class Application
{
   ...
   public static final fflib_Application.TriggerHandlerFactory TriggerHandler =
       new fflib_Application.TriggerHandlerFactory(
            new Map<SObject, Type>
            {
                  Account.SObjectType => AccountsTriggerHandler.class,
                  ...
            });
}
----

*Trigger class*
[source, java]
----

trigger Accounts on Account
        (after delete, after insert, after update, before delete, before insert, before update)
{
    Application.TriggerHandler.handle(AccountsTriggerHandler.class);
}
----

*Alternatively*
[source, java]
----
trigger Accounts on Account
        (after delete, after insert, after update, before delete, before insert, before update)
{
    fflib_SObjectDomain.triggerHandler(AccountsTriggerHandler.class);
}
----

== Trigger Handler

=== Naming conventions
Use the plural name of your Custom Object for the name of your trigger handler appended with 'TriggerHandler'.

=== Event Methods
The methods names are typically constructed from the following three elements;

1. EventType for object
1. condition
1. business logic

The condition can be omitted when the business logic need to be performed on all records.

Some examples of valid names are:


[source, java]
----
onChangedEmployeeNumberForPartnerAccountsRecalculateDiscount
<-------- 1 ----------><------- 2 ------><------- 3 ------->

onChangedEmployeeNumberRecalculateRating
<-------- 1 ----------><------ 3 ------>
----

The methods will also process the logic in the same order:

1. Validate that there are records meeting the event criteria +
    They use the method `getChangedRecords` +
    followed by a guard clause to halt further execution when there are no records meeting the criteria

1. Validate the condition +
    Typically creating a new domain with the changedRecords and using one or more selector methods from the domain +
    followed by a guard clause to halt further execution when there are no records in the domain meeting the condition

1. Invoke business logic +
    Either invokes a business logic method on the domain, if the scope is limited to the contents of a domain. Otherwise it invokes a service layer method, passing the domain as argument.



=== Example

[source, java]
----
public class AccountsTriggerHandler extends fflib_SObjectDomain
{
    private AccountsTriggerHandler(List<Opportunity> sObjectList)
    {
        super(sObjectList);
    }

    public override void onBeforeInsert()
    {
        calculateRating();
    }

    public override void onBeforeUpdate()
    {
        onChangedEmployeeNumberRecalculateRating();
        onChangedEmployeeNumberForPartnerAccountsRecalculateDiscount();
    }

    private void calculateRating();
    {
        Accounts
            .newInstance(Records)
            .recalculateRating(Records);
    }

    private void onChangedEmployeeNumberRecalculateRating()
    {
        // First validate the event "onChangedEmployeeNumbers"
        List<Account> changedRecords =getChangedRecords(
                new Set<Schema.SObjectField>{ Schema.Account.NumberOfEmployees }
        );

        if (changedRecords.isEmpty()) return;

        // Secondly call the business logic "RecalculateRating"
        Accounts.newInstance(changedRecords)
            .recalculateRating();
    }

    private void onChangedEmployeeNumberForPartnerAccountsRecalculateDiscount()
    {
        // First validate the event "onChangedEmployeeNumbers"
        List<Account> changedRecords =getChangedRecords(
                new Set<Schema.SObjectField>{ Schema.Account.NumberOfEmployees }
        );

        if (changedRecords.isEmpty()) return;

        // Secondly validate the condition "ForPartnerAccounts"
        Accounts partnerAccounts =
                Accounts.newInstance(changedRecords)
                        .selectByRecordType(Account.RecordtType.Partner);

        if (partnerAccounts.isEmpty()) return;

        // Thirdly call the business logic "RecalculateDiscount"
        AccountsService.RecalculateDiscount();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new AccountsTriggerHandler(sObjectList);
        }
    }
}